### ISSUE TITLE
NN model support

### ISSUE THREAD

**Issue by JiTao3** [learnedsystems/RMI#10]
I noticed that more complex NN models could be used in the paper powered by TensorFlow. But there are only simple models here? How can I build an RMI with a more complex NN model? @RyanMarcus @anikristo

**Comment by RyanMarcus** [comment]
This RMI implementation is focused on in-memory scenarios. When dealing with in-memory data, a NN model's inference time will generally be too high (it would be faster just to binary search the whole dataset). So there is no implementation of NNs here.
