### ISSUE TITLE
cleanup() should only be called on malloc'ed model parameters

### ISSUE THREAD

**Issue by marcelmaltry** [learnedsystems/RMI#2]
Hi, I just trained a model with two `linear_spline` layers and a `branching_factor` of 200,000, i.e.
```
cargo run --release -- somedata_100M_uint64 sosd_rmi linear_spline,linear_spline 200000
``` 

The resulting C++ program does not compile with the following error:
```
sosd_rmi.cpp:11:5: error: no matching function for call to 'free'
    free(L1_PARAMETERS);
    ^~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/malloc/_malloc.h:42:7: note: candidate function not viable: no known conversion from 'const double [400000]' to 'void *' for 1st argument
void     free(void *);
         ^
1 error generated.
```

It seems like in the `cleanup()` function, `free` is called on `L1_PARAMETERS` although it was not allocated with `malloc`. 

Looking at `codegen::generate_code()` `free_code` should possibly only be generated in case `storage` has value `StorageConf::Disk(path)`, not in case of `StorageConf::Embed`.

**Comment by RyanMarcus** [comment]
Doh! Good catch. I'll start working on this. Looking to remove support for the Embed configuration anyway, since it leads to really long compile times of the C code.

**Comment by RyanMarcus** [comment]
Alright, should be fixed now. I changed the default behavior to include model errors, so check the updated README as well. :)
