### ISSUE TITLE
Multiple layers

### ISSUE THREAD

**Issue by r-barnes** [learnedsystems/RMI#5]
Trying to train with three layers fails:
```
cargo run --release -- books_200M_uint32 my_first_rmi linear,linear,linear 100
    Finished release [optimized + debuginfo] target(s) in 0.02s
     Running `target/release/rmi /z/downloads/books_200M_uint32 my_first_rmi linear,linear,linear 100`
thread 'main' panicked at 'explicit panic', <::std::macros::panic macros>:2:4
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Is this because of an intentional limitation on the number of layers or some other issue?

**Comment by RyanMarcus** [comment]
Yes, we've decided to only support 2-level RMIs in this implementation. We haven't encountered a dataset for which a 3-level RMI wasn't beat out by some other 2-layer RMI, and only supporting two RMI layers greatly simplified the code.

Older versions of this RMI implementations supported an arbitrary number of layers -- if you need 3+ layer RMIs, I can find the revision for you.

**Comment by r-barnes** [comment]
I wonder if it would be possible to edit the README file to reflect this? I could also submit a PR.

**Comment by quito418** [comment]
Hi, can you let us know the revision version of multi-layer RMI

thank you
